# Generated by Django 4.2.20 on 2025-03-14 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='payslips/%Y/%m/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', "En attente d'analyse"), ('processing', "En cours d'analyse"), ('completed', 'Analyse terminée'), ('error', "Erreur lors de l'analyse")], default='pending', max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
