# Generated by Django 4.2.20 on 2025-04-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='anonymized_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/%Y/%m/'),
        ),
    ]
