# Generated by Django 4.2.20 on 2025-04-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_payslip_anonymized_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='anonymized_file',
        ),
    ]
