# Generated by Django 4.2.20 on 2025-04-16 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_remove_payslip_anonymized_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Fiche de paie', 'verbose_name_plural': 'Fiches de paie'},
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='period',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='status',
        ),
        migrations.AddField(
            model_name='payslip',
            name='contractual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire brut mensuel contractuel'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='convention_collective',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Convention collective'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='daily_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Heures travaillées par jour (moyenne)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Traitement terminé'), ('error', 'Erreur de traitement')], default='pending', max_length=20, verbose_name='Statut de traitement'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload"),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='uploaded_file',
            field=models.FileField(upload_to='payslips/', verbose_name='Fichier téléchargé'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
