# Generated by Django 4.2.20 on 2025-04-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'employé"),
        ),
        migrations.AddField(
            model_name='payslip',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire net extrait'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Période de la fiche de paie'),
        ),
    ]
