# Generated by Django 4.2.20 on 2025-05-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_payslip_employee_name_payslip_net_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='daily_hours',
        ),
        migrations.AddField(
            model_name='payslip',
            name='additional_details',
            field=models.TextField(blank=True, null=True, verbose_name="Détails supplémentaires fournis par l'utilisateur"),
        ),
    ]
