# Generated by Django 4.2.20 on 2025-07-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_payslip_daily_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='convention_collective',
            field=models.CharField(choices=[('SYNTEC', 'Syntec'), ('HCR', 'Hôtels, Cafés, Restaurants'), ('METALLURGIE', 'Métallurgie'), ('AUTRE', 'Autre / Non spécifiée')], default='AUTRE', max_length=50, verbose_name='Convention collective applicable'),
        ),
    ]
