# Generated by Django 4.2.20 on 2025-07-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_payslip_convention_collective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='convention_collective',
            field=models.CharField(choices=[('SYNTEC', 'Syntec'), ('HCR', 'Hôtels, Cafés, Restaurants (HCR)'), ('METALLURGIE', 'Métallurgie (Nouvelle convention)'), ('COMMERCE', 'Commerce de détail et de gros'), ('AUTRE', 'Autre / Non spécifiée')], default='AUTRE', max_length=50, verbose_name='Convention collective applicable'),
        ),
    ]
