# Generated by Django 4.2.20 on 2025-08-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_payslip_convention_collective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='convention_collective',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Convention collective'),
        ),
    ]
