# Generated by Django 4.2.20 on 2025-08-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_payslip_convention_collective'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='period_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de période (format date)'),
        ),
    ]
