# Generated by Django 4.2.20 on 2025-08-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_payslip_period_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='analysis_type',
            field=models.CharField(default='single', max_length=20, verbose_name="Type d'analyse"),
        ),
    ]
