# Generated by Django 4.2.20 on 2025-08-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_payslip_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('APPRENTI', 'Apprenti'), ('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGIAIRE', 'Stagiaire'), ('TEMPS_PARTIEL', 'Temps partiel'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name="Statut d'emploi"),
        ),
        migrations.AddField(
            model_name='payslip',
            name='expected_smic_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage du SMIC attendu pour cette période (ex: 75 pour 75%)', max_digits=5, null=True, verbose_name='Pourcentage SMIC attendu'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='working_time_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Ratio temps de travail (1.00 = temps plein, 0.80 = 80%)', max_digits=5, null=True, verbose_name='Ratio temps de travail'),
        ),
    ]
