# Generated by Django 4.2.20 on 2025-08-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_payslip_employment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('payment_required', 'Paiement requis'), ('processing', 'En cours de traitement'), ('completed', 'Traitement terminé'), ('error', 'Erreur de traitement')], default='pending', max_length=20, verbose_name='Statut de traitement'),
        ),
    ]
