# Generated by Django 4.2.20 on 2025-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_payslip_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/', verbose_name='Fichier téléchargé'),
        ),
    ]
