# Generated by Django 4.2.20 on 2025-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_uploaded_file_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='file_deleted',
            field=models.BooleanField(default=False, verbose_name='Fichier supprimé après analyse'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de fichier d'origine"),
        ),
    ]
