# Generated by Django 4.2.20 on 2025-03-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('warning', 'Avertissement')], max_length=20)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('payslip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='documents.payslip')),
            ],
            options={
                'verbose_name': 'Analyse de fiche de paie',
                'verbose_name_plural': 'Analyses de fiches de paie',
            },
        ),
    ]
