# Generated by Django 4.2.20 on 2025-03-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipanalysis',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
