# Generated by Django 4.2.20 on 2025-04-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_payslipanalysis_is_anonymized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslipanalysis',
            name='is_anonymized',
        ),
    ]
