# Generated by Django 4.2.20 on 2025-04-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_payslipanalysis_is_anonymized'),
    ]

    operations = [
    ]
