# Generated by Django 4.2.20 on 2025-08-05 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_payslip_convention_collective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0004_remove_is_anonymized'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAnalysisGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('name', models.CharField(default='Analyse groupée', max_length=255, verbose_name="Nom de l'analyse")),
                ('convention_collective', models.CharField(choices=[('SYNTEC', 'Syntec'), ('HCR', 'Hôtels, Cafés, Restaurants (HCR)'), ('METALLURGIE', 'Métallurgie'), ('COMMERCE', 'Commerce de détail et de gros'), ('AUTRE', 'Autre / Non spécifiée')], default='AUTRE', max_length=50, verbose_name='Convention collective')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminée'), ('error', 'Erreur')], default='pending', max_length=20, verbose_name='Statut')),
                ('total_files', models.IntegerField(default=0, verbose_name='Nombre total de fichiers')),
                ('processed_files', models.IntegerField(default=0, verbose_name='Fichiers traités')),
                ('total_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant total dû')),
                ('missing_benefits', models.JSONField(blank=True, default=dict, verbose_name='Avantages manquants')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Résumé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_analysis_groups', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Analyse groupée',
                'verbose_name_plural': 'Analyses groupées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='payslipanalysis',
            name='analysis_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'analyse"),
        ),
        migrations.AlterField(
            model_name='payslipanalysis',
            name='analysis_details',
            field=models.JSONField(blank=True, default=dict, verbose_name="Détails de l'analyse"),
        ),
        migrations.AlterField(
            model_name='payslipanalysis',
            name='analysis_status',
            field=models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('warning', 'Avertissement')], max_length=20, verbose_name="Statut de l'analyse"),
        ),
        migrations.AlterField(
            model_name='payslipanalysis',
            name='payslip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='documents.payslip', verbose_name='Fiche de paie'),
        ),
        migrations.CreateModel(
            name='BulkAnalysisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analysis.bulkanalysisgroup', verbose_name="Groupe d'analyse")),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_analysis_items', to='documents.payslip', verbose_name='Fiche de paie')),
            ],
            options={
                'verbose_name': "Élément d'analyse groupée",
                'verbose_name_plural': "Éléments d'analyse groupée",
                'ordering': ['order'],
                'unique_together': {('group', 'payslip')},
            },
        ),
    ]
